name: DevMMO
version: '${version}'
main: com.teenkung.devmmo.DevMMO
api-version: '1.20'
depend:
  - MythicMobs
  - MythicLib
  - MMOCore
  - WorldGuard
commands:
  spawn-mythicmobs:
    aliases:
      - summon-mythicmobs
      - smm
      - summonmythic
    permission: op
    permission-message: "don't"
  devmmo:
    permission: op
    permission-message: "don't"
  bossreminder:
    description: Toggle boss spawn reminder notifications for yourself
    permission: ''
    permission-message: ''

permissions:
  elytra.bypass:
    description: Allows using fireworks to boost elytra speed
    default: false
  devmmo.reload:
    description: Allows reloading the DevMMO plugin
    default: op
  devmmo.bossspawner:
    description: Allows force-spawning bosses via BossSpawner
    default: op